# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('volume', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
            ],
        ),
    ]
